dist: trusty
sudo: required

services:
  - docker

jobs:
  include:

    - stage: unit tests
      language: go
      go: 1.11
      script:
        - make test

    - stage: docker images
      language: go
      go: 1.11
      script:
        - make docker
